- name: Instalar WordPress
  hosts: all
  become: yes
  vars:
    db_name: wordpress
    db_user: wordpress
    db_password: unir12345
    wp_path: /var/www/html/wordpress
    wp_title: 'Ansible con Wordpress - Christian Lopez Baya'
    wp_admin_user: unir
    wp_admin_password: unir12345
    wp_admin_email: unir_christian@example.com

  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes necesarios
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - apache2
        - php
        - libapache2-mod-php
        - php-mysql
        - php-curl
        - php-gd
        - php-mbstring
        - php-xml
        - unzip

    - name: Descargar e instalar WordPress
      get_url:
        url: 'https://wordpress.org/latest.zip'
        dest: '/tmp/wordpress.zip'

    - name: Descomprimir WordPress
      unarchive:
        src: '/tmp/wordpress.zip'
        dest: '/var/www/html/'
        remote_src: yes

    - name: Configurar Apache para apuntar a la nueva carpeta
      ansible.builtin.lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: "^\\s*DocumentRoot"
        line: '    DocumentRoot /var/www/html/wordpress'
      notify: restart apache2

    - name: Descargar WP-CLI
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar'
        dest: '/usr/local/bin/wp'
        mode: '0755'

    - name: Install MySQL
      apt:
        name:
          - mysql-server
          - python-mysqldb
        state: present
        update_cache: yes

    - name: Crear base de datos y usuario en MySQL
      mysql_db:
        name: '{{ db_name }}'
        state: present

    - name: Crear usuario MySQL
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        host: localhost
        priv: '*.*:ALL'
      notify: restart apache2

    - name: Configurar wp-config.php
      template:
        src: wp-config.php
        dest: '/var/www/html/wordpress/wp-config.php'
      notify: restart apache2

    - name: Instalar WordPress con WP-CLI
      ansible.builtin.command:
        cmd: 'wp core install --url=http://localhost:9000 --title="{{ wp_title }}" --admin_user="{{ wp_admin_user }}" --admin_password="{{ wp_admin_password }}" --admin_email="{{ wp_admin_email }}" --path="{{ wp_path }}" --allow-root'
      become: yes

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
